### ISSUE TITLE
When playing multi-audiotrack file and switch between tracks, track audios will lose some.

### ISSUE THREAD

**Issue by jianguile** [valoroso-dev/BikPlayer#2]
using current version, the issue will easy reproduce.

**Comment by valoroso-dev** [comment]
interesting , please send your test file .

**Comment by valoroso-dev** [comment]
[fix lost data when playing multiaudiotrack ](919769796847f8411eca388d28866e546b7998a0)

**Comment by jianguile** [comment]
It works well, thanks.
