### ISSUE TITLE
Play raw h.264 stream issue

### ISSUE THREAD

**Issue by xfirefly** [valoroso-dev/BikPlayer#5]
Play raw h.264 stream, no audio,  there is a few seconds delay.
Is it because pts == AV_NOPTS_VALUE ? How to fix it, thanks

**Comment by xfirefly** [comment]
When playing audio only, aac files, there will be no sound output

 `ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "vn", 1);
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "nodisp", 1);
`

**Comment by valoroso-dev** [comment]
I will check the relevant part.

**Comment by valoroso-dev** [comment]
“a few delay” means slow to play?

**Comment by valoroso-dev** [comment]
everything looks well here.
"a few second delay" means slow to start ?
could you submit more information?

**Comment by xfirefly** [comment]
> everything looks well here. "a few second delay" means slow to start? Maybe there is something wrong with the file format. could you submit more information? The raw h.264 file and aac file

[test.zip](https://github.com/valoroso-dev/BikPlayer/files/10342838/test.zip)
We are using it for screen mirroring, see attached h264 file

**Comment by valoroso-dev** [comment]
> > everything looks well here. "a few second delay" means slow to start? Maybe there is something wrong with the file format. could you submit more information? The raw h.264 file and aac file
> 
> [test.zip](https://github.com/valoroso-dev/BikPlayer/files/10342838/test.zip) We are using it for screen mirroring, see attached h264 file

I did a test with this file in Android System (Xiaomi 12) sdk 31, the situation is like this
1) The fps stays at 25 with avcodec decoder and the video play normal
2) There was some issues with MediaCodec decoder such as playback well fast then normal with 30fps, but I did not analyze the reasons in detail
How about try to use avcodec decoder?

**Comment by valoroso-dev** [comment]
There are some frames in the video that do not change, and the delay you mentioned may be caused by this.
In addition, raw H264 does not contain pts, ffmpeg will set a default fps which is 25 when playing.
You can also control the playback speed through the setpts parameter of ffmpeg's avfilter. For example, setpts=N/(25*TB) means setting a fixed frame rate of 25. For more usage, please refer to the ffmpeg documentation.

**Comment by xfirefly** [comment]
> There are some frames in the video that do not change, and the delay you mentioned may be caused by this. In addition, raw H264 does not contain pts, ffmpeg will set a default fps which is 25 when playing. You can also control the playback speed through the setpts parameter of ffmpeg's avfilter. For example, setpts=N/(25*TB) means setting a fixed frame rate of 25. For more usage, please refer to the ffmpeg documentation.

Thank you very much, when mirroring, the iOS transfer video is at variable frame rate (1 - 60fps), I want to minimize the latency, how to set the pts or modify the BikPlayer code

**Comment by valoroso-dev** [comment]
> > There are some frames in the video that do not change, and the delay you mentioned may be caused by this. In addition, raw H264 does not contain pts, ffmpeg will set a default fps which is 25 when playing. You can also control the playback speed through the setpts parameter of ffmpeg's avfilter. For example, setpts=N/(25*TB) means setting a fixed frame rate of 25. For more usage, please refer to the ffmpeg documentation.
> 
> Thank you very much, when mirroring, the iOS transfer video is at variable frame rate (1 - 60fps), I want to minimize the latency, how to set the pts or modify the BikPlayer code

Now BikPlayer is playing this file at the default 25fps. In fact, your request is equivalent to playing at a variable speed. How will the player recognize when to use which speed? My suggestion is to see if there is a way to get the content that meets your requirements from the place where the content is generated. If you want to use BikPlayer to achieve it, you can look at the configure_video_filters function of ffplay.c, which contains how to set the filter and just has a setpts example of.

**Comment by xfirefly** [comment]
Many thanks
